import 'package:carmarketapp/models/db/brands_model.dart';

class CarBrands {
  static List<BrandModel> carBrands = [
    BrandModel(brandName: "Abadal"),
    BrandModel(brandName: "Abarth"),
    BrandModel(brandName: "Abbott-Detroit"),
    BrandModel(brandName: "ABT"),
    BrandModel(brandName: "AC"),
    BrandModel(brandName: "Acura"),
    BrandModel(brandName: "Aiways"),
    BrandModel(brandName: "Aixam"),
    BrandModel(brandName: "Alfa Romeo"),
    BrandModel(brandName: "Alpina"),
    BrandModel(brandName: "Alpine"),
    BrandModel(brandName: "Alta"),
    BrandModel(brandName: "Alvis"),
    BrandModel(brandName: "AMC"),
    BrandModel(brandName: "Apollo"),
    BrandModel(brandName: "Arash"),
    BrandModel(brandName: "Arcfox"),
    BrandModel(brandName: "Ariel"),
    BrandModel(brandName: "ARO"),
    BrandModel(brandName: "Arrival"),
    BrandModel(brandName: "Arrinera"),
    BrandModel(brandName: "Artega"),
    BrandModel(brandName: "Ascari"),
    BrandModel(brandName: "Askam"),
    BrandModel(brandName: "Aspark"),
    BrandModel(brandName: "Aston Martin"),
    BrandModel(brandName: "Atalanta"),
    BrandModel(brandName: "Auburn"),
    BrandModel(brandName: "Audi"),
    BrandModel(brandName: "Audi Sport"),
    BrandModel(brandName: "Austin"),
    BrandModel(brandName: "Autobacs"),
    BrandModel(brandName: "Autobianchi"),
    BrandModel(brandName: "Axon"),
    BrandModel(brandName: "BAC"),
    BrandModel(brandName: "BAIC Motor"),
    BrandModel(brandName: "Baojun"),
    BrandModel(brandName: "BeiBen"),
    BrandModel(brandName: "Bentley"),
    BrandModel(brandName: "Berkeley"),
    BrandModel(brandName: "Berliet"),
    BrandModel(brandName: "Bertone"),
    BrandModel(brandName: "Bestune"),
    BrandModel(brandName: "BharatBenz"),
    BrandModel(brandName: "Bitter"),
    BrandModel(brandName: "Bizzarrini"),
    BrandModel(brandName: "BMW"),
    BrandModel(brandName: "BMW M"),
    BrandModel(brandName: "Borgward"),
    BrandModel(brandName: "Bowler"),
    BrandModel(brandName: "Brabus"),
    BrandModel(brandName: "Brammo"),
    BrandModel(brandName: "Brilliance"),
    BrandModel(brandName: "Bristol"),
    BrandModel(brandName: "Brooke"),
    BrandModel(brandName: "Bufori"),
    BrandModel(brandName: "Bugatti"),
    BrandModel(brandName: "Buick"),
    BrandModel(brandName: "BYD"),
    BrandModel(brandName: "Byton"),
    BrandModel(brandName: "Cadillac"),
    BrandModel(brandName: "CAMC"),
    BrandModel(brandName: "Canoo"),
    BrandModel(brandName: "Caparo"),
    BrandModel(brandName: "Carlsson"),
    BrandModel(brandName: "Caterham"),
    BrandModel(brandName: "Changan"),
    BrandModel(brandName: "Changfeng"),
    BrandModel(brandName: "Chery"),
    BrandModel(brandName: "Chevrolet Corvette"),
    BrandModel(brandName: "Chevrolet"),
    BrandModel(brandName: "Chrysler"),
    BrandModel(brandName: "Cisitalia"),
    BrandModel(brandName: "Citroën"),
    BrandModel(brandName: "Cizeta"),
    BrandModel(brandName: "Cole"),
    BrandModel(brandName: "Corre La Licorne"),
    BrandModel(brandName: "Dacia"),
    BrandModel(brandName: "Daewoo"),
    BrandModel(brandName: "DAF"),
    BrandModel(brandName: "Daihatsu"),
    BrandModel(brandName: "Daimler"),
    BrandModel(brandName: "Dartz"),
    BrandModel(brandName: "Datsun"),
    BrandModel(brandName: "David Brown"),
    BrandModel(brandName: "Dayun"),
    BrandModel(brandName: "De Tomaso"),
    BrandModel(brandName: "Delage"),
    BrandModel(brandName: "DeSoto"),
    BrandModel(brandName: "Detroit Electric"),
    BrandModel(brandName: "Devel Sixteen"),
    BrandModel(brandName: "Diatto"),
    BrandModel(brandName: "DINA"),
    BrandModel(brandName: "DKW"),
    BrandModel(brandName: "DMC"),
    BrandModel(brandName: "Dodge"),
    BrandModel(brandName: "Dodge Viper"),
    BrandModel(brandName: "Dongfeng"),
    BrandModel(brandName: "Donkervoort"),
    BrandModel(brandName: "Drako"),
    BrandModel(brandName: "DS"),
    BrandModel(brandName: "Duesenberg"),
    BrandModel(brandName: "Eagle"),
    BrandModel(brandName: "EDAG"),
    BrandModel(brandName: "Edsel"),
    BrandModel(brandName: "Eicher"),
    BrandModel(brandName: "Elemental"),
    BrandModel(brandName: "Elfin"),
    BrandModel(brandName: "Elva"),
    BrandModel(brandName: "Englon"),
    BrandModel(brandName: "ERF"),
    BrandModel(brandName: "Eterniti"),
    BrandModel(brandName: "Exeed"),
    BrandModel(brandName: "9ff"),
    BrandModel(brandName: "Facel Vega"),
    BrandModel(brandName: "Faraday Future"),
    BrandModel(brandName: "FAW"),
    BrandModel(brandName: "FAW Jiefang"),
    BrandModel(brandName: "Ferrari"),
    BrandModel(brandName: "Fiat"),
    BrandModel(brandName: "Fioravanti"),
    BrandModel(brandName: "Fisker"),
    BrandModel(brandName: "Foden"),
    BrandModel(brandName: "Force Motors"),
    BrandModel(brandName: "Ford"),
    BrandModel(brandName: "Ford Mustang"),
    BrandModel(brandName: "Foton"),
    BrandModel(brandName: "FPV"),
    BrandModel(brandName: "Franklin"),
    BrandModel(brandName: "Freightliner"),
    BrandModel(brandName: "FSO"),
  ];
}
